// Local HTTPS dev server for the Checkpoint PWA.
//
// Service worker registration and PWA install prompts only work over HTTPS or
// localhost — the certificate generated by mkcert (in tools/local-ssl/) lets you
// hit the app over HTTPS from your phone on the same Wi-Fi, which is the only
// realistic way to test "Add to Home Screen" against a real iOS/Android browser.
//
// Usage:
//   node tools/serve.mjs                # https://localhost:8443/
//   PORT=4443 node tools/serve.mjs
//
// To regenerate certs (after a network change or for additional hosts):
//   cd tools/local-ssl
//   mkcert -cert-file localhost.pem -key-file localhost-key.pem \
//          localhost 127.0.0.1 ::1 <your-LAN-ip>

import https from 'node:https';
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const PORT = Number(process.env.PORT ?? 8443);

const CERT_DIR = path.join(__dirname, 'local-ssl');
const CERT_FILE = path.join(CERT_DIR, 'localhost.pem');
const KEY_FILE = path.join(CERT_DIR, 'localhost-key.pem');

if (!fs.existsSync(CERT_FILE) || !fs.existsSync(KEY_FILE)) {
  console.error(`Missing cert at ${CERT_FILE}.`);
  console.error(`Generate one with: cd tools/local-ssl && mkcert localhost 127.0.0.1 <lan-ip>`);
  process.exit(1);
}

const TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.mjs': 'application/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.webmanifest': 'application/manifest+json',
};

const server = https.createServer(
  {
    cert: fs.readFileSync(CERT_FILE),
    key: fs.readFileSync(KEY_FILE),
  },
  (req, res) => {
    let pathname;
    try {
      pathname = decodeURIComponent(new URL(req.url, 'https://x').pathname);
    } catch {
      res.statusCode = 400;
      return res.end('bad request');
    }
    if (pathname.endsWith('/')) pathname += 'index.html';
    const filePath = path.join(ROOT, pathname);
    if (!filePath.startsWith(ROOT)) {
      res.statusCode = 403;
      return res.end('forbidden');
    }
    fs.readFile(filePath, (err, data) => {
      if (err) {
        res.statusCode = 404;
        return res.end('not found');
      }
      const ext = path.extname(filePath).toLowerCase();
      res.setHeader('Content-Type', TYPES[ext] ?? 'application/octet-stream');
      // Disable caching during dev so a hard reload is enough to see changes.
      res.setHeader('Cache-Control', 'no-store');
      res.end(data);
    });
  }
);

server.listen(PORT, () => {
  console.log(`Checkpoint dev server: https://localhost:${PORT}/`);
  console.log(`(also reachable on https://<your-LAN-ip>:${PORT}/ if your cert covers it)`);
});

process.on('SIGINT', () => {
  console.log('\nshutting down');
  server.close(() => process.exit(0));
});
